import { ArrowUpRight, CalendarClock, MapPin } from 'lucide-react'
import { assetUrl } from '../../lib/api'
import type { EventItem } from '../../types/event'

type PublicEventCardProps = { event: EventItem; onOpen: () => void; index: number }
const gradients = ['from-cyan-950 via-cyan-700 to-cyan-400', 'from-slate-950 via-cyan-900 to-teal-400', 'from-cyan-900 via-sky-700 to-cyan-200']
export function PublicEventCard({ event, onOpen, index }: PublicEventCardProps) {
  const date = new Date(event.startDate); const closed = event.registrationOpen === false; const initials = event.title.split(' ').slice(0, 2).map((word) => word[0]).join('').toUpperCase()
  return <button disabled={closed} onClick={onOpen} className={`group overflow-hidden rounded-2xl border border-cyan-100 bg-white text-left shadow-sm transition ${closed ? 'cursor-not-allowed opacity-75' : 'hover:-translate-y-1 hover:shadow-xl hover:shadow-cyan-900/10'}`}><div style={event.imageUrl ? { backgroundImage: `url(${assetUrl(event.imageUrl)})`, backgroundSize: 'cover', backgroundPosition: 'center' } : { backgroundImage: `linear-gradient(135deg, ${event.backgroundColor1 ?? '#083344'}, ${event.backgroundColor2 ?? '#06b6d4'})` }} className={`relative flex h-40 items-center justify-center overflow-hidden ${event.imageUrl ? '' : `bg-linear-to-br ${gradients[index % gradients.length]}`}`}>{event.imageUrl && <div className="absolute inset-0 bg-cyan-950/35" />}{!event.imageUrl && <><div className="absolute -right-8 -top-10 size-40 rounded-full border-20 border-white/10" /><div className="absolute -bottom-16 -left-10 size-44 rounded-full border-24 border-white/10" /><span className="relative font-display text-5xl font-semibold tracking-widest text-white/90">{initials}</span></>}{closed ? <span className="absolute left-4 top-4 rounded-full bg-white/95 px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-rose-600">Closed</span> : <span className="absolute right-4 top-4 grid size-9 place-items-center rounded-full bg-white/90 text-cyan-950 opacity-0 transition group-hover:opacity-100"><ArrowUpRight size={17} /></span>}</div><div className="p-5"><h2 className="truncate font-display text-lg font-semibold text-cyan-950">{event.title}</h2><p className="mt-1 line-clamp-2 min-h-10 text-sm leading-5 text-slate-500">{event.description || 'Join us for this upcoming event.'}</p><div className="mt-5 space-y-2 text-xs text-slate-500"><span className="flex items-center gap-2"><CalendarClock size={15} className="text-cyan-600" />{date.toLocaleDateString('en', { month: 'short', day: 'numeric', year: 'numeric' })} · {date.toLocaleTimeString('en', { hour: 'numeric', minute: '2-digit' })}</span>{event.location && <span className="flex items-center gap-2"><MapPin size={15} className="text-cyan-600" />{event.location}</span>}</div></div></button>
}
