import { useState } from 'react'
import { CalendarClock, MapPin, Pencil, Trash2 } from 'lucide-react'
import { assetUrl } from '../../lib/api'
import type { EventItem } from '../../types/event'

type EventCardProps = { event: EventItem; onOpen: () => void; onRegistrations?: () => void; onEdit: () => void; onDelete: () => void }
export function EventCard({ event, onOpen, onRegistrations, onEdit, onDelete }: EventCardProps) {
  const [now] = useState(() => Date.now()); const start = new Date(event.startDate); const isPast = start.getTime() < now; const initials = event.title.split(' ').slice(0, 2).map((word) => word[0]).join('').toUpperCase()
  return <article onClick={onOpen} className="cursor-pointer overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-cyan-900/10"><div style={event.imageUrl ? { backgroundImage: `url(${assetUrl(event.imageUrl)})`, backgroundSize: 'cover', backgroundPosition: 'center' } : { backgroundImage: `linear-gradient(135deg, ${event.backgroundColor1 ?? '#083344'}, ${event.backgroundColor2 ?? '#06b6d4'})` }} className="relative flex h-36 items-center justify-center overflow-hidden">{!event.imageUrl && <span className="font-display text-5xl font-semibold tracking-widest text-white/90">{initials}</span>}<div className="absolute right-3 top-3 flex gap-1"><button title="Registrations" onClick={(clickEvent) => { clickEvent.stopPropagation(); onRegistrations?.() }} className="rounded-md bg-white/90 px-2 py-1 text-xs font-bold text-cyan-950 shadow-sm">Guests</button><button title="Edit event" onClick={(clickEvent) => { clickEvent.stopPropagation(); onEdit() }} className="grid size-8 place-items-center rounded-md bg-white/90 text-cyan-950 shadow-sm"><Pencil size={14} /></button><button title="Delete event" onClick={(clickEvent) => { clickEvent.stopPropagation(); onDelete() }} className="grid size-8 place-items-center rounded-md bg-white/90 text-slate-500 shadow-sm hover:text-rose-600"><Trash2 size={14} /></button></div></div><div className="p-4"><h3 className="truncate font-display text-base font-semibold text-slate-800">{event.title}</h3><p className="mt-1 truncate text-xs text-slate-500">{event.description || 'No description added yet.'}</p><div className="mt-4 space-y-2 border-t border-slate-100 pt-3 text-xs text-slate-500"><span className="flex items-center gap-2"><CalendarClock size={14} className="text-cyan-600" />{start.toLocaleDateString('en', { month: 'short', day: 'numeric', year: 'numeric' })} · {start.toLocaleTimeString('en', { hour: 'numeric', minute: '2-digit' })}</span>{event.location && <span className="flex items-center gap-2"><MapPin size={14} className="text-cyan-600" />{event.location}</span>}</div><div className="mt-4 text-[11px] font-semibold"><span className={isPast ? 'text-slate-400' : 'text-emerald-600'}>● {isPast ? 'Past' : 'Upcoming'}</span></div></div></article>
}
